name: Build and Deploy all platforms

on:
  push:
    tags: ['v*.*.*']

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml

  build-windows:
    uses: ./.github/workflows/build-windows.yml

  build-apk:
    uses: ./.github/workflows/build-apk.yml

  deploy:
    needs: [
      build-linux,
      build-apk,
      build-windows
    ]
    name: Deploy Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

# ---------- UPLOAD ARTIFACTS TO THE RELEASE

## Release APK

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-${{ github.ref }}
          path: ./dist/

      - name: Release APK artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.apk
          asset_name: "DiceGame-debug${{ github.ref }}.apk"
          asset_content_type: application/vnd.android.package-archive

## Release Linux binaries

      - name: Download Linux AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: appimage-${{ github.ref }}

      - name: Release Linux AppImage artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.AppImage
          asset_name: "ThreeGame-linux${{ github.ref }}.AppImage"
          asset_content_type: application/x-appimage

## Release Windows binaries

      - name: Download Windows EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-${{ github.ref }}

      - name: Release Windows EXE artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.exe
          asset_name: "ThreeGame-windows${{ github.ref }}.exe"
          asset_content_type: application/vnd.microsoft.portable-executable