name: Build Android APK

on:
  push:
    branches: [ capacitor ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build

      - name:  Add android folder if not present
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Sync Capacitor
        run: npx cap sync

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Check folder content of android output
        run: ls ./android/app/build/outputs/apk/debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DiceGame-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
      
      - name: Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          name: "Release: ${{ github.sha }}"
          body: "Automated debug release for ${{ github.sha }}"
          files: android/app/build/outputs/apk/debug/app-debug.apk
          draft: false
          prerelease: false